In [140]:
!pip install pandas sqlalchemy psycopg[binary] openpyxl

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: psycopg[binary] in c:\users\hp\anaconda3\lib\site-packages (3.3.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: psycopg-binary==3.3.6 in c:\users\hp\anaconda3\lib\site-packages (from psycopg[binary]) (3.3.6)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [141]:
import pandas as pd
import numpy as np

In [142]:
df = pd.read_excel("Ecommerce_Unclean_Project.xlsx")

In [143]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [144]:
df.info()    #if column type is object then it is textual column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [145]:
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [146]:
df.shape

(524, 15)

In [147]:
#check missing values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [148]:
#check duplicate records
df.duplicated().sum()

np.int64(11)

In [149]:
#Remove duplicate records  
#inplace true likhne se jo original value h usme change ho jata h 
df.drop_duplicates(inplace=True)

In [150]:
df.shape

(513, 15)

In [151]:
df.duplicated().sum()

np.int64(0)

In [152]:
#replace invalid values
#replaceing common invalid values with NaN   
#replace kr rha h n/a,null or empty values ko nan se
df.replace(['N/A','NULL',''],np.nan,inplace=True)

In [153]:
# remove extra spaces
#lambda function
#hum space unn jgh se hi htate h jha text hota h kyuki numeric value me agr spaces honge bhi toh bhi dikkat ni h koi  
#humare pass x data/variable h uske upr hum konsa operation perform krna h vo hume vo hum lambda function me btate h
# df = df.apply(lambda x: x.str.strip() if x.dtype =='object' else x)

# Remove extra spaces only from text values
df = df.apply(
    lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x)
    if col.dtype == 'object'
    else col
)

# Replace empty strings with NaN after removing spaces
df.replace(['N/A', 'NULL', ''], np.nan, inplace=True)

In [154]:
#standardized text format
# convert text into proper case 
#case sensitivity ko htane ke lie kia h ye 
#title name ka function hi proper case ke lie use kia jata h 
df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()

In [155]:
#validate email address
#keep only valid records
df = df[df['Email'].str.contains('@',na = False)]

# • df['Email']: Selects the column named 'Email' from your DataFrame.
# • .str.contains('@'): Checks each text value in that column to see if it contains the @ symbol. It returns True if it does, and False if it does not.
# • na = False: Handles missing or empty data (NaN). If a row has a missing email, it explicitly sets the result to False so the program doesn't crash or include empty values.
# • df[...]: Uses the resulting list of True and False values to filter the data. Only rows marked True are kept.

In [156]:
#Convert data columns 
#to_datetime function se hum values ko date and time me convert kr dete h 
df['Order_Date']= pd.to_datetime(df['Order_Date'],errors='coerce',format='mixed', dayfirst=True)    #NaT
df['Delivery_Date']= pd.to_datetime(df['Delivery_Date'],errors='coerce',format='mixed', dayfirst=True)

#errors='coerce':handles messy or corrupted data. If a row contains text that isn't a real date (for example, "Missing", "N/A", or a typo like "32/12/2025"), setting this to 'coerce' will automatically turn that invalid entry into NaT (Not a Time) instead of throwing an error and crashing your code.
#format is mixed bcoz dataset contains date like dd-mm-yyyy, mm-dd-yyyy, yyyy-dd-mm so mixed format helps python to work on all date types
#dayfirst =  true handles when we can not decide wheather month is first or date like 02-03-2005 we dont know its feb or march so in this dayfirst makesure that the day is first and the month is march
#by default pandas take month first thatswhy we use dayfirst

In [157]:
#convert numeric columns 
cols = ['Qty','Unit_Price','Discount']

for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')   

# humne ek for loop bnya h jisse hum sari values ko jo bhi cols me h unko numeric datatype me kr denge agr vo datatype change nhi hoga toh vo hume Nan dega

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 497 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       491 non-null    object
 1   Order_Date     485 non-null    datetime64[ns]
 2   Customer_Name  497 non-null    object
 3   Email          497 non-null    object
 4   Phone          475 non-null    float64
 5   City           497 non-null    object
 6   State          497 non-null    object
 7   Product        497 non-null    object
 8   Category       497 non-null    object
 9   Qty            433 non-null    float64
 10  Unit_Price     447 non-null    float64
 11  Discount       354 non-null    float64
 12  Payment_Mode   497 non-null    object
 13  Order_Status   497 non-null    object
 14  Delivery_Date  476 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(9)
memory usage: 62.1+ KB

In [159]:
# remove invalid quantity
#remove records having negative or zero quantity

df = df[df['Qty']>0]

#jo main dataset h usme bss whi columns bache h jisme quanntity ki value 0 se upr se kyuki agr quantity zero is not possible

In [160]:
#fill missing values 


# 1. Add this at the top to opt-in to the future behavior and silence the warning
pd.set_option('future.no_silent_downcasting', True)  #this is mainly to silence the warning and giving pandas the right to change and handle datatype in future

#original code 
df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [161]:
#Feature Engineering
#Total sales

df['Sales'] = df['Qty']*df['Unit_Price']

In [162]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-05-08,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-18,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-16,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-03-09,2997.0

In [163]:
#Net amount
df['Net_Amount'] = df['Sales']-(df['Sales']*df['Discount']/100)

In [164]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.00
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.00
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-05-08,5997.0,5697.15
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0,2998.00
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-16,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0,2997.00
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15

In [165]:
#Profit (Exapmle:20%)
df['Profit']=df['Net_Amount']*0.20

In [166]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0,2998.00,599.60
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-16,NaN,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43

In [167]:
#order month 
df['Month'] = df['Order_Date'].dt.month_name()

#The .dt in code is a pandas Accessor object used to extract datetime properties from a Series. like date from orderdate columns , year from it etc

In [168]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20,June
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20,February
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43,May
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52,February
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0,2998.00,599.60,March
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-16,NaN,NaN,NaN,April
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43,March

In [169]:
#order year 
df['Year'] = df['Order_Date'].dt.year

In [170]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20,February,2025.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52,February,2025.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,2025-03-28,2998.0,2998.00,599.60,March,2025.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-16,NaN,NaN,NaN,April,2025.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025.0

In [171]:
#Weekday 
df['Weekday'] = df['Order_Date'].dt.day_name()

In [172]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-07-03,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-02-09,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2025-05-08,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-18,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-27,39996.0,39996.00,7999.20,February,2025.0,Monday
520,ORD1609,2025-03-21,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,2025-03-28,2998.0,2998.00,599.60,March,2025.0,Friday
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2025-04-16,NaN,NaN,NaN,April,2025.0,Thursday
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-16,2997.0,2997.00,599.40,January,2025.0,Saturday
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2025-03-09,2997.0,2847.15,569.43,March,2025.0,Monday

In [173]:
#Final data Validation 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    object
 1   Order_Date     368 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          380 non-null    object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  378 non-null    datetime64[ns]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          368 non-null    object
 19  Year           368 non-null    float64
 20  Weekday        368 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 65.3+ KB

In [174]:
df.isnull().sum()

Order_ID          6
Order_Date       12
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Sales            37
Net_Amount       37
Profit           37
Month            12
Year             12
Weekday          12
dtype: int64

In [175]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,368,380.000000,343.000000,380.000000,378,343.000000,343.000000,343.000000,368.0
mean,2025-04-04 10:26:05.217391360,3.328947,3252.352770,7.802632,2025-04-10 08:41:54.285714432,11103.664723,10249.073324,2049.814665,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-05 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 18:00:00,2.000000,999.000000,0.000000,2025-02-23 00:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 12:00:00,3.000000,1999.000000,5.000000,2025-04-13 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-17 12:00:00,5.000000,4999.000000,15.000000,2025-05-25 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,7.881075,NaN,12194.528486,11506.169779,2301.233956,0.0

In [176]:
# export clean data 
df.to_csv("Clean_Ecommerce.csv",index = False)

In [177]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\hp\anaconda3\lib\site-packages (2.9.13)

In [178]:
#connection to database 

from sqlalchemy import create_engine

# Format syntax: postgresql+psycopg2://<user>:<password>@localhost:5432/ecommerce
# Update 'YOUR_PASSWORD' with your exact PostgreSQL master login password
engine = create_engine('postgresql+psycopg2://postgres:kirtika123@localhost:5432/DA_Ecommerce')

In [179]:
# df.to_sql(
#     name='orders',
#     con=engine,
#     if_exists='replace',
#     index=False
# )

from sqlalchemy import text

# Connect and drop the dependent view
with engine.connect() as conn:
    conn.execute(text("DROP VIEW IF EXISTS my_saved_query;"))
    conn.commit()

# Now run your pandas code safely
df.to_sql(
    name='orders',
    con=engine,
    if_exists='replace',
    index=False
)

# Recreate your view afterward if you still need it
with engine.connect() as conn:
    conn.execute(text("""
        CREATE VIEW my_saved_query AS 
        SELECT * FROM orders; -- Replace this with your actual view logic
    """))
    conn.commit()

In [180]:
#this is used to find the the error if any happened when we connect to the data base  

try:
    with engine.connect() as conn:
        print("Connection successful!")
except Exception as e:
    print(f"Error details: {e}")

Connection successful!

In [181]:
df.shape

(380, 21)

In [182]:
df['Discount'].head(20)

0      0.0
1     20.0
2      5.0
5     20.0
6      0.0
7      0.0
8      0.0
9      0.0
10     5.0
13     5.0
14    20.0
15    10.0
16     5.0
17     0.0
18     0.0
19     5.0
21     5.0
22    15.0
24    10.0
26     0.0
Name: Discount, dtype: float64

In [183]:
print("Final rows:", len(df))
print("Order IDs:", df['Order_ID'].notna().sum())

Final rows: 380
Order IDs: 374

In [184]:
df[df['Order_Date'].isna()][
    ['Order_ID', 'Order_Date', 'Month', 'Profit']
]

    Order_ID Order_Date Month   Profit
38   ORD1040        NaT   NaN  1349.10
78   ORD1080        NaT   NaN  1424.05
118  ORD1120        NaT   NaN  1599.68
158  ORD1160        NaT   NaN  3199.68
198  ORD1200        NaT   NaN  1139.24
238  ORD1240        NaT   NaN   359.82
278  ORD1280        NaT   NaN  1439.28
318  ORD1320        NaT   NaN   899.82
358  ORD1360        NaT   NaN   399.80
398  ORD1400        NaT   NaN  1279.36
438  ORD1440        NaT   NaN  1699.66
478  ORD1480        NaT   NaN  3399.32

In [185]:
print("Missing Order_Date:", df['Order_Date'].isna().sum())
print("Missing Month:", df['Month'].isna().sum())
print("Missing Profit:", df['Profit'].isna().sum())

Missing Order_Date: 12
Missing Month: 12
Missing Profit: 37